// Code generated by "stringer -type=Suit"; DO NOT EDIT.

package card

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Spade-0]
	_ = x[Club-1]
	_ = x[Diamon-2]
	_ = x[Heart-3]
}

const _Suit_name = "SpadeClubDiamonHeart"

var _Suit_index = [...]uint8{0, 5, 9, 15, 20}

func (i Suit) String() string {
	if i < 0 || i >= Suit(len(_Suit_index)-1) {
		return "Suit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Suit_name[_Suit_index[i]:_Suit_index[i+1]]
}
